// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"npanel-migrator/internal/biz"
	"npanel-migrator/internal/conf"
	"npanel-migrator/internal/data"
	"npanel-migrator/internal/server"
	"npanel-migrator/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp 装配 Kratos 应用。
// 实际实现在 wire 生成的 wire_gen.go 中。
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	confServer := newConfProviders(bootstrap)
	dataData, cleanup, err := data.NewData()
	if err != nil {
		return nil, nil, err
	}
	migrationUsecase := biz.NewMigrationUsecase(dataData)
	migrationService := service.NewMigrationService(migrationUsecase)
	httpServer := server.NewHTTPServer(confServer, migrationService)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// newConfProviders 把 Bootstrap 拆成 server 层需要的 conf.Server。
func newConfProviders(bc *conf.Bootstrap) *conf.Server {
	return bc.Server
}
